# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ik8s-demo2
  labels:
    app: ik8s-demo2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ik8s-demo2
  template:
    metadata:
      labels:
        app: ik8s-demo2
    spec:
      containers:
      - name: ik8s-demo2
        image: uk.icr.io/lureyit/ik8s:demo2
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
        - name: CLOUDANT_IAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: iamApiKey
              optional: true

