# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-k8s-yaml
  labels:
    app: node-k8s-yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-k8s-yaml
  template:
    metadata:
      labels:
        app: node-k8s-yaml
    spec:
      containers:
      - name: node-k8s
        image: uk.icr.io/luis/node-k8s:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
        - name: CLOUDANT_IAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: iamApiKey
              optional: true

